<?php

namespace Zhongfu\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormSeminarFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormSeminarFileRepository extends EntityRepository
{
}
